# Generated by Django 2.2.9 on 2020-01-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0002_auto_20200107_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
