# Generated by Django 2.2.9 on 2020-02-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0003_userprofileinfo_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
