# Generated by Django 3.0 on 2019-12-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='toppings',
            field=models.ManyToManyField(to='product.Topping'),
        ),
    ]
