# Generated by Django 2.2.9 on 2020-01-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comission', models.IntegerField(default=0, verbose_name='Comission')),
                ('is_percentage', models.BooleanField(default=False, verbose_name='Is percentage?')),
            ],
            options={
                'verbose_name': 'Comission',
                'verbose_name_plural': 'Comission',
            },
        ),
    ]
