# Generated by Django 2.2.9 on 2020-01-28 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comission',
            options={'verbose_name': 'Admin Comission', 'verbose_name_plural': 'Admin Comission'},
        ),
    ]
