# Generated by Django 2.2.9 on 2020-01-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(blank=True, null=True, verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_title',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Title'),
        ),
    ]
