# Generated by Django 2.2.9 on 2020-02-06 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_auto_20200108_0702'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0003_auto_20200111_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user_id', 'restaurant_id')},
        ),
    ]
