# Generated by Django 2.2.9 on 2020-01-27 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispute', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispute',
            old_name='completed_on',
            new_name='closed_on',
        ),
    ]
