# Generated by Django 3.0 on 2020-01-02 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0005_auto_20200102_0822'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreFollower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_name', models.CharField(max_length=42)),
                ('restaurant_name', models.CharField(max_length=42)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('restaurant_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='restaurant.Restaurant')),
                ('user_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='followed_stores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
