# Generated by Django 3.0 on 2020-01-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_follower', '0002_auto_20200102_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storefollower',
            name='follower_name',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='storefollower',
            name='restaurant_name',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
