# Generated by Django 3.0 on 2020-01-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_follower', '0003_auto_20200102_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storefollower',
            old_name='created_on',
            new_name='followed_on',
        ),
    ]
