# Generated by Django 3.0 on 2020-01-02 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0005_auto_20200102_0822'),
        ('store_follower', '0004_auto_20200102_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefollower',
            name='is_followed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='storefollower',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='restaurant.Restaurant', verbose_name='Restaurant'),
        ),
        migrations.AlterField(
            model_name='storefollower',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_stores', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
