# Generated by Django 2.2.9 on 2020-01-05 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_follower', '0005_auto_20200102_0926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storefollower',
            options={'verbose_name': 'Follower', 'verbose_name_plural': 'Followers'},
        ),
    ]
