# Generated by Django 3.0 on 2019-12-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='logo',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_banner_image',
            field=models.ImageField(blank=True, upload_to='restaurant/images/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_logo',
            field=models.ImageField(blank=True, upload_to='restaurant/images/'),
        ),
    ]
