# Generated by Django 3.0 on 2019-12-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20191218_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
