# Generated by Django 3.0 on 2019-12-22 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0003_restaurant_restaurant_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='follower',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
