# Generated by Django 3.0 on 2020-01-02 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20200102_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='follower',
        ),
    ]
