# Generated by Django 2.2.9 on 2020-01-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_remove_restaurant_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='newfields',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
