# Generated by Django 2.2.9 on 2020-01-03 02:20

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_remove_restaurant_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=django_google_maps.fields.AddressField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
    ]
