# Generated by Django 2.2.9 on 2020-01-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20200103_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_address',
            field=models.CharField(blank=True, max_length=42, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_banner_image',
            field=models.ImageField(blank=True, upload_to='restaurant/images/', verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_logo',
            field=models.ImageField(blank=True, upload_to='restaurant/images/', verbose_name='Logo'),
        ),
    ]
