# Generated by Django 2.2.9 on 2020-01-07 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
        ('restaurant', '0009_auto_20200107_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='Location.Address'),
        ),
    ]
