# Generated by Django 3.0 on 2019-12-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='addons',
            field=models.ManyToManyField(to='food.Addon'),
        ),
    ]
