# Generated by Django 3.0 on 2019-12-18 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20191218_0407'),
        ('food', '0002_food_addons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='addons',
            field=models.ManyToManyField(blank=True, to='food.Addon'),
        ),
        migrations.AlterField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='restaurant.Restaurant'),
        ),
    ]
