# Generated by Django 3.0 on 2019-12-22 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20191218_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='sale_price',
        ),
    ]
