# Generated by Django 3.0 on 2020-01-01 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import food.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0004_remove_food_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='created_by',
            field=models.ForeignKey(default=food.middleware.CurrentUserMiddleware.get_current_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='addons', to=settings.AUTH_USER_MODEL),
        ),
    ]
