# Generated by Django 3.0 on 2020-01-01 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurant_follower'),
        ('food', '0007_auto_20200101_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='restaurant.Restaurant'),
        ),
    ]
