# Generated by Django 2.2.9 on 2020-02-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20200103_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
