# Generated by Django 3.0 on 2019-12-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20191222_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('processing', 'Processing'), ('accepted', 'Accepted'), ('driver_assigned', 'Driver Assigned'), ('cancel', 'Canceled'), ('completed', 'Completed')], default='processing', max_length=40),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn')], default='p', max_length=1),
        ),
    ]
