# Generated by Django 3.0 on 2019-12-22 10:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_remove_food_sale_price'),
        ('sales', '0004_auto_20191222_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item_name', models.CharField(max_length=50, verbose_name='Item Name')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Quantiy')),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='food.Food')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Order')),
            ],
            options={
                'verbose_name': 'Order Items',
            },
        ),
    ]
