# Generated by Django 2.2.9 on 2020-01-14 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20200101_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurant.Restaurant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='seller_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='food_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='food.Food'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='sales.Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Item Name'),
        ),
    ]
