# Generated by Django 2.2.9 on 2020-01-20 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20200114_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='food_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='food.Food'),
        ),
    ]
