# Generated by Django 2.2.9 on 2020-02-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20200120_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Order Name'),
        ),
    ]
